// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtTjFiZVuV07xK2RybRSVb0zLSEAoGBrg',
    appId: '1:481424336718:web:cb5737de1e298d0d7a201f',
    messagingSenderId: '481424336718',
    projectId: 'jobfind-3d2ec',
    authDomain: 'jobfind-3d2ec.firebaseapp.com',
    storageBucket: 'jobfind-3d2ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyJp3T2sfDjNIbu7HcC8Q9ImnyKC6M4Y',
    appId: '1:481424336718:android:2ebe5ccccc3767057a201f',
    messagingSenderId: '481424336718',
    projectId: 'jobfind-3d2ec',
    storageBucket: 'jobfind-3d2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3pwnDPHdYoBUeiPDFzSSuzIEAEY6KJM',
    appId: '1:481424336718:ios:1411ee4a913e92947a201f',
    messagingSenderId: '481424336718',
    projectId: 'jobfind-3d2ec',
    storageBucket: 'jobfind-3d2ec.appspot.com',
    iosBundleId: 'com.example.job',
  );
}
